/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as MijnAanvragenRouteImport } from './routes/mijn-aanvragen'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AanvragenRouteImport } from './routes/aanvragen'
import { Route as IndexRouteImport } from './routes/index'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const MijnAanvragenRoute = MijnAanvragenRouteImport.update({
  id: '/mijn-aanvragen',
  path: '/mijn-aanvragen',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AanvragenRoute = AanvragenRouteImport.update({
  id: '/aanvragen',
  path: '/aanvragen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanvragen': typeof AanvragenRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/mijn-aanvragen': typeof MijnAanvragenRoute
  '/profiel': typeof ProfielRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanvragen': typeof AanvragenRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/mijn-aanvragen': typeof MijnAanvragenRoute
  '/profiel': typeof ProfielRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanvragen': typeof AanvragenRoute
  '/admin': typeof AdminRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/mijn-aanvragen': typeof MijnAanvragenRoute
  '/profiel': typeof ProfielRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanvragen'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/history'
    | '/inventory'
    | '/mijn-aanvragen'
    | '/profiel'
    | '/request'
    | '/settings'
    | '/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanvragen'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/history'
    | '/inventory'
    | '/mijn-aanvragen'
    | '/profiel'
    | '/request'
    | '/settings'
    | '/statistics'
  id:
    | '__root__'
    | '/'
    | '/aanvragen'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/history'
    | '/inventory'
    | '/mijn-aanvragen'
    | '/profiel'
    | '/request'
    | '/settings'
    | '/statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanvragenRoute: typeof AanvragenRoute
  AdminRoute: typeof AdminRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  MijnAanvragenRoute: typeof MijnAanvragenRoute
  ProfielRoute: typeof ProfielRoute
  RequestRoute: typeof RequestRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijn-aanvragen': {
      id: '/mijn-aanvragen'
      path: '/mijn-aanvragen'
      fullPath: '/mijn-aanvragen'
      preLoaderRoute: typeof MijnAanvragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanvragen': {
      id: '/aanvragen'
      path: '/aanvragen'
      fullPath: '/aanvragen'
      preLoaderRoute: typeof AanvragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanvragenRoute: AanvragenRoute,
  AdminRoute: AdminRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  MijnAanvragenRoute: MijnAanvragenRoute,
  ProfielRoute: ProfielRoute,
  RequestRoute: RequestRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
